# A. Vector

## Pendefinisian

In [ ]:
# Import Libray

import numpy as np

In [ ]:
# Pendefinisian Vector

a = [1, 2, 3]
vect_a = np.array(a)
vect_a

array([1, 2, 3])

## Operasi Aritmatika (Penjumlahan, Pengurangan, dan Pembagian)

In [ ]:
# Operasi Aritmatika (Penjumlahan, Pengurangan, dan Pembagian) dengan Bilangan Skalar

print('Penjumlahan : ', vect_a + 2)
print('Pengurangan : ', vect_a - 2)
print('Pembagian   : ', vect_a/2)

Penjumlahan :  [3 4 5]
Pengurangan :  [-1  0  1]
Pembagian   :  [0.5 1.  1.5]


In [ ]:
# Operasi Aritmatika (Penjumlahan, Pengurangan, dan Pembagian) dengan Sesama Vector

b = [4, 5, 6]
vect_b = np.array(b)

print('Penjumlahan : ', vect_a + vect_b)
print('Pengurangan : ', vect_a - vect_b)
print('Pembagian   : ', vect_a / vect_b)

Penjumlahan :  [5 7 9]
Pengurangan :  [-3 -3 -3]
Pembagian   :  [0.25 0.4  0.5 ]


## Vector Norm

In [ ]:
# Mencari Vector Norm

d = [8, 6]
vect_d = np.array(d)

print('L1 - Manhattan Distance')
print(np.linalg.norm(vect_d, 1))
print('')

print('L2 - Euclidean Distance')
print(np.linalg.norm(vect_d))
print(np.linalg.norm(vect_d, 2))

L1 - Manhattan Distance
14.0

L2 - Euclidean Distance
10.0
10.0


## Operasi Perkalian

In [ ]:
# Operasi Perkalian dengan Bilangan

e = [1, 2 , 3]
vect_e = np.array(e)

print(vect_e * 2)

[2 4 6]


In [ ]:
# Operasi Perkalian dengan Sesama Vector

f = [1, 2, 3]
g = [4, 5, 6] 

vect_f = np.array(f)
vect_g = np.array(g)

print('Hasil Perkalian - Element Wise')
print(vect_f * vect_g)
print('')

print('Hasil Perkalian - Dot Product')
print(vect_f @ vect_g)
print(vect_f.dot(vect_g))
print(np.dot(vect_f, vect_g))

Hasil Perkalian - Element Wise
[ 4 10 18]

Hasil Perkalian - Dot Product
32
32
32


## Cosine Similarity

In [ ]:
# Cosine Similarity

k = [8, 0]
m = [6, 0]

vect_k = np.array(k)
vect_m = np.array(m)

cos_theta = (vect_k @ vect_m) / (np.linalg.norm(vect_k) * np.linalg.norm(vect_m))
cos_theta

1.0

In [ ]:
# Mencari Radian dan Degree

radian = np.arccos(cos_theta)
degree = np.degrees(radian)

print('Radian : ', radian)
print('Degree : ', degree)

Radian :  0.0
Degree :  0.0


## Studi Kasus

```
teks_1 = saya pergi ke rumah kakek saya
teks_2 = saya pergi ke rumah nenek saya
```

In [ ]:
# Pendefinisian Vector

t1 = [2, 1, 1, 1, 1, 0]
t2 = [2, 1, 1, 1, 0, 1]

vect_t1 = np.array(t1)
vect_t2 = np.array(t2)

cos_theta = (vect_t1 @ vect_t2) / (np.linalg.norm(vect_t1) * np.linalg.norm(vect_t2))
cos_theta

0.8749999999999998

In [ ]:
# Melihat Ukuran Vector `vec_t1`

vect_t1.shape

(6,)

# B. Matrix

## Pendefinisian

In [ ]:
# Pendefinisian Matrix

A = [[1, 2, 3],
     [4, 5, 6]]

matrix_A = np.array(A)
matrix_A

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# Melihat Ukuran `matrix_A`

matrix_A.shape

(2, 3)

## Operasi Aritmatika

In [ ]:
# Operasi Aritmatika terhadap Matrix dengan Bilangan

print('Penjumlahan : \n', matrix_A + 2)
print('')

print('Pengurangan : \n', matrix_A - 2)
print('')

print('Perkalian   : \n', matrix_A * 2)
print('')

print('Pembagian   : \n', matrix_A / 2)
print('')

Penjumlahan : 
 [[3 4 5]
 [6 7 8]]

Pengurangan : 
 [[-1  0  1]
 [ 2  3  4]]

Perkalian   : 
 [[ 2  4  6]
 [ 8 10 12]]

Pembagian   : 
 [[0.5 1.  1.5]
 [2.  2.5 3. ]]



In [ ]:
# Pendefinisian Matrix B

B = [[7, 8, 9],
     [10, 11, 12]]

matrix_B = np.array(B)
matrix_B

array([[ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
# Operasi Aritmatika Antar Sesama Matrix

print('Penjumlahan : \n', matrix_A + matrix_B)
print('')

print('Pengurangan : \n', matrix_A - matrix_B)
print('')

print('Perkalian   : \n', matrix_A * matrix_B)
print('')

print('Pembagian   : \n', matrix_A / matrix_B)
print('')

Penjumlahan : 
 [[ 8 10 12]
 [14 16 18]]

Pengurangan : 
 [[-6 -6 -6]
 [-6 -6 -6]]

Perkalian   : 
 [[ 7 16 27]
 [40 55 72]]

Pembagian   : 
 [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]



In [ ]:
# Perkalian Vector (Matrix Multiplication)

A = [[1, 2],
     [3, 4],
     [5, 6]]

B = [[1, 2],
     [3, 4]]

matrix_A = np.array(A)
matrix_B = np.array(B)

print(matrix_A @ matrix_B)

[[ 7 10]
 [15 22]
 [23 34]]


## Pembuktian Perkalian dengan Identity Matrix

In [ ]:
# Pembuktian Matrix Identitas

C = [[1, 2, 3], 
     [4, 5, 6],
     [7, 8, 9]]

matrix_C = np.array(C)
print(matrix_C)
print('')

matrix_D = np.eye(3, 3)
print(matrix_D)
print('')

print(matrix_C @ matrix_D)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
